<a href="https://colab.research.google.com/github/ApoorvaNagarajan/Image-Filter-Kernels/blob/master/assignment19/assignment19.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importing all python packages**

In [1]:
import keras
import json
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
import numpy as np

Using TensorFlow backend.


**Load the annotations file**

In [0]:
with open('via_export_json.json') as f:
  data = json.load(f)

In [3]:
rectangles = []

for i in data : 
    image_data = data[i]
    regions = image_data['regions']
    for r in regions:
      shape = r['shape_attributes']
      rectangles.append([shape['x'], shape['y'], shape['width'], shape['height']])
      #print(i, shape) 
      
print(np.array(rectangles))

[[ 42  64 153 163]
 [217  60 149 227]
 [ 46  78 108 146]
 ...
 [ 25  96 107 243]
 [134  11  88 198]
 [228 152 146 219]]


**Run k means clustering on all the bounding boxes**

In [0]:
kmeans = KMeans(n_clusters=4, random_state=0).fit(np.array(rectangles))

In [5]:
kmeans.cluster_centers_

array([[ 63.51612903,  45.32258065,  71.74193548, 110.66666667],
       [263.03061224,  44.17346939,  71.57142857, 113.09183673],
       [166.58333333,  92.96666667,  53.43333333,  79.5       ],
       [124.07692308,  36.26923077, 132.15384615, 224.73076923]])